CREATE TABLE users (
name VARCHAR(25) PRIMARY KEY,
hash_code VARCHAR(255) NOT NULL,
display_name VARCHAR(100) NOT NULL,
enabled BOOLEAN NOT NULL DEFAULT TRUE);

CREATE TABLE sessions (
id VARCHAR(36) NOT NULL PRIMARY KEY,
name_user VARCHAR(25) NOT NULL,
expiry_date TIMESTAMP);